/**
 * Environment Type Definitions
 *
 * TypeScript types for Cloudflare Workers environment bindings
 * - D1 Database
 * - KV Namespace (AUTH_KV)
 * - Queue (EVENT_QUEUE)
 * - Workflow (PROCESS_EVENT_WORKFLOW - Epic 2.3)
 * - Environment variables
 */

/**
 * Cloudflare Workers Environment Bindings
 *
 * All bindings configured in wrangler.toml
 *
 * Note: D1Database, KVNamespace, Queue types are globally available
 * from worker-configuration.d.ts (generated by wrangler types)
 */
export interface Env {
	/**
	 * D1 Database binding for event storage
	 * Schema: events table with event_id, payload, metadata, status, timestamps
	 */
	DB: D1Database;

	/**
	 * KV Namespace for authentication tokens
	 * Key format: token:{token_value}
	 */
	AUTH_KV: KVNamespace;

	/**
	 * KV Namespace for metrics tracking
	 * Stores event counts, processing stats, and performance metrics
	 */
	METRICS_KV: KVNamespace;

	/**
	 * Queue binding for event processing
	 * Producer: API worker sends events
	 * Consumer: Queue worker processes batches
	 */
	EVENT_QUEUE: Queue<unknown>;

	/**
	 * Workflow binding for event processing pipeline
	 * Implemented in Epic 2.3
	 * Handles: validation, storage, metrics
	 */
	PROCESS_EVENT_WORKFLOW: Workflow;

	/**
	 * Environment identifier
	 * Used for conditional behavior (logging, rate limits, etc.)
	 */
	ENVIRONMENT: 'development' | 'production';

	/**
	 * Log level configuration
	 * Controls verbosity of structured logging
	 */
	LOG_LEVEL: 'debug' | 'info' | 'warn' | 'error';
}
